<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class FacialRecognitionVisitationRequest extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'facial_recognition_log_id',
        'visitor_id',
        'inmate_id',
        'visit_date',
        'visit_time',
        'duration_minutes',
        'status',
        'rejection_reason',
        'notes',
        'checked_in_at',
        'checked_out_at',
        'approved_by',
        'approved_at',
        'is_auto_generated',
    ];

    protected $casts = [
        'visit_date' => 'date',
        'visit_time' => 'datetime',
        'checked_in_at' => 'datetime',
        'checked_out_at' => 'datetime',
        'approved_at' => 'datetime',
        'is_auto_generated' => 'boolean',
        'duration_minutes' => 'integer',
    ];

    /**
     * Get the facial recognition log that generated this request
     */
    public function facialRecognitionLog(): BelongsTo
    {
        return $this->belongsTo(FacialRecognitionLog::class);
    }

    /**
     * Get the visitor for this request
     */
    public function visitor(): BelongsTo
    {
        return $this->belongsTo(Visitor::class);
    }

    /**
     * Get the inmate for this request
     */
    public function inmate(): BelongsTo
    {
        return $this->belongsTo(Inmate::class);
    }

    /**
     * Get the officer who approved this request
     */
    public function approvedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'approved_by');
    }

    /**
     * Scope for pending requests
     */
    public function scopePending($query)
    {
        return $query->where('status', 'pending');
    }

    /**
     * Scope for approved requests
     */
    public function scopeApproved($query)
    {
        return $query->where('status', 'approved');
    }

    /**
     * Scope for completed visits
     */
    public function scopeCompleted($query)
    {
        return $query->where('status', 'completed');
    }

    /**
     * Scope for auto-generated requests
     */
    public function scopeAutoGenerated($query)
    {
        return $query->where('is_auto_generated', true);
    }

    /**
     * Check if the request is currently active (visitor is present)
     */
    public function isActive(): bool
    {
        return $this->checked_in_at !== null && $this->checked_out_at === null;
    }

    /**
     * Approve the request
     */
    public function approve(int $approvedById): bool
    {
        $this->status = 'approved';
        $this->approved_by = $approvedById;
        $this->approved_at = now();
        return $this->save();
    }

    /**
     * Reject the request
     */
    public function reject(string $reason): bool
    {
        $this->status = 'rejected';
        $this->rejection_reason = $reason;
        return $this->save();
    }

    /**
     * Check-in visitor
     */
    public function checkIn(): bool
    {
        $this->checked_in_at = now();
        $this->status = 'approved';
        return $this->save();
    }

    /**
     * Check-out visitor
     */
    public function checkOut(): bool
    {
        $this->checked_out_at = now();
        $this->status = 'completed';
        return $this->save();
    }
}
